START = "1"
STOP = "2"
FILENAME = "3"
OK_START = "4"
OK_STOP = "5"
OK_FILENAME = "6"
OK_CALIBRATE = "q"
ISSUE = "a"
CLOSE = "8"
CALIBRATE = "9"
CLIENT = False
SERVER = True

CONNECT_STATUS = 1
ACQUISITION_STATUS = 2
FILE_STATUS = 3
CALIBRATE_STATUS = 4
ISSUES = 5


CONNECT_ERROR = -1
ACQUISITION_ERROR = -2
FILE_ERROR = -3
CALIBRATE_ERROR = -4